GET http://localhost:3000/

###
# redirect
GET http://localhost:3000/api/redirect

###
# asterisk test
GET http://localhost:3000/api/abTESTTESTcd

###
# dynamic params
GET http://localhost:3000/api/books/narnia/5

###
# route handler
GET http://localhost:3000/api/book

###
# erorr handling
GET http://localhost:3000/error

###
POST http://localhost:3000/api/data HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "test": true
}

###
# chain request test
GET http://localhost:3000/api/chainrequest
###
PUT http://localhost:3000/api/chainrequest
###
POST http://localhost:3000/api/chainrequest